---
title: "p8105_hw5_niz2000"
author: "Nora Zakaria"
date: "11/11/2019"
output: github_document
---

# Problem 1

## Load Tidyverse and the Iris Data
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
iris_with_missing
```


## Function to Replace Missing Values
```{r Function to Replace Missing Values}
replace_missing = function(x) {
  if (is.numeric(x)) {
    ifelse(is.na(x), mean(x, na.rm = TRUE), x)
  } else if (is.character(x)) {
    ifelse(is.na(x), "virginica", x)
  }
}
iris_complete = map_df(iris_with_missing, replace_missing)
iris_complete
```


# Problem 2

## Load in the HW 5 Zipfile Data
```{r}
data_df = tibble(
  participant = list.files(path = "./data")
)
data_df
```


## Iterate over Files Names
```{r} 
data_df = function(path){
  case_control_df = read_csv(path)
  case_control_df 
}
directory = "./data"
study_df = tibble(
  observation = list.files(path = "./data"),
    files = str_c(directory, "/",observation)) %>%
  mutate(
    weekly_data = map(files, read_csv),
    observation = str_replace(observation, ".csv","")) %>%
  unnest() %>%
  rename(participant = observation) %>%
  mutate(
    study_arm = if_else(participant %in% c("con_01", "con_02", "con_03", "con_04", "con_05",
        "con_06", "con_07", "con_08", "con_09", "con_10"), "control", participant),
    study_arm = if_else(study_arm %in% c("exp_01", "exp_02", "exp_03", "exp_04", "exp_05",
        "exp_06", "exp_07", "exp_08", "exp_09", "exp_10"), "experimental", study_arm)) %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "weekly_observation") 
study_df
```
 
    
## Spaghetti Plot of Observations for Each Subject Over Time
```{r Spaghetti Plot}
study_df %>% 
  group_by(participant, week) %>% 
  ggplot(aes(x = week, y = weekly_observation, group = participant, color = study_arm)) +
  geom_line() +
  labs(caption = "Observations for Each Subject Over Time") + 
  viridis::scale_color_viridis(
    discrete = TRUE)
```


# Problem 3

## Set the Regression Design Elements
```{r}
linear_regression= function(n = 30, beta0 = 2, beta1 = 0) {
  regression_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 50^0.5)
  )
  
  ls_fit = lm(y ~ x, data = regression_data) 
  
  broom::tidy(ls_fit) %>%
    filter(term == "x")
}

  regression_results = rerun(10000, linear_regression()) %>%
    bind_rows()
  
  results = tibble(
    beta1 = c(0, 1, 2, 3, 4, 5, 6)) %>%
    mutate(
      output_list = map(.x = beta1, ~rerun(10000, linear_regression(beta1 = .x))),
      estimate_dfs = map(output_list, bind_rows)) %>%
    select(-output_list) %>%
    unnest(estimate_dfs)
results
```


## Plot Showing the Proportion of Times the Null was Rejected

```{r}
results %>%
  mutate(
    rejection = if_else(p.value < 0.05, "rejected", p.value),
    rejection = if_else(rejection >= 0.05, "fail_to_reject", rejection)) %>%
  ggplot(aes(x = estimate, y = rejected)) + 
  geom_line()
```


## Plot Showing the Average Estimate and True Value of Beta 1
```{r}

```

